/* BioTuring 互動式考題 — 題庫資料（中英雙語）
 * Bilingual question bank for the BioTuring Interactive Tutorial.
 * 題型 type: "single" 單選 | "multi" 多選 | "tf" 是非
 * 單選 ans:"A".."D" ; 多選 ans:["A","C"] ; 是非 ans:"T"|"F"
 * 中文欄位：stem/A/B/C/D/exp ; 英文欄位：stem_en/A_en/B_en/C_en/D_en/exp_en
 */
window.QUIZ_DATA = {
  bioturing: {
    label: "BioTuring 互動考題",
    label_en: "BioTuring Interactive Quiz",
    labels_en: {
      "平台入門": "Getting Started",
      "總覽 (Overview)": "Overview",
      "資料匯入與格式": "Data Import & Formats",
      "BBrowserX 核心流程": "BBrowserX Core Pipeline",
      "品質管控 (QC)": "Quality Control (QC)",
      "標準化與降維": "Normalization & Dim-Reduction",
      "分群與批次校正": "Clustering & Batch Correction",
      "細胞註釋 (Annotation)": "Cell Annotation",
      "差異表達與 Venice": "Differential Expression & Venice",
      "進階與生態系": "Advanced & Ecosystem",
      "軌跡與細胞通訊": "Trajectory & Cell Communication",
      "多模態與免疫圖譜": "Multimodal & Immune Profiling",
      "SpatialX 空間分析": "SpatialX Spatial Analysis",
      "Talk2Data 資料庫": "Talk2Data Database"
    },
    subjects: {
      "平台入門": {
        "總覽 (Overview)": [
          { type:"single",
            stem:"BioTuring 平台系列最核心的設計理念是什麼？",
            stem_en:"What is the core design philosophy of the BioTuring platform family?",
            A:"只服務會寫 R 的資深生物資訊學家", A_en:"Serving only senior bioinformaticians who code in R",
            B:"提供無程式碼 (no-code) 的 GUI，讓不會寫程式的科學家也能分析單細胞與空間資料", B_en:"A no-code GUI so scientists without coding skills can analyze single-cell & spatial data",
            C:"取代所有雲端運算", C_en:"Replacing all cloud computing",
            D:"僅做原始定序 (base calling)", D_en:"Only performing raw base calling",
            ans:"B",
            exp:"BioTuring 的定位是把標準流程「按鈕化」，服務沒有程式經驗的 wet-lab 研究者。",
            exp_en:"BioTuring turns the standard pipeline into buttons, serving wet-lab researchers without coding experience." },
          { type:"single",
            stem:"下列哪個平台是 BioTuring 用來分析單細胞 RNA-seq 的旗艦工具？",
            stem_en:"Which platform is BioTuring's flagship tool for single-cell RNA-seq?",
            A:"SmartBulk", A_en:"SmartBulk",
            B:"SpatialX", B_en:"SpatialX",
            C:"BBrowserX", C_en:"BBrowserX",
            D:"Talk2Data", D_en:"Talk2Data",
            ans:"C",
            exp:"BBrowserX（含 Pro 版）是單細胞 RNA-seq 分析的旗艦平台，Pro 版可擴展到 10M+ 細胞。",
            exp_en:"BBrowserX (incl. Pro) is the flagship single-cell RNA-seq platform; Pro scales to 10M+ cells." },
          { type:"multi",
            stem:"下列哪些是 BioTuring 生態系中的平台？（多選）",
            stem_en:"Which of the following are platforms in the BioTuring ecosystem? (multiple)",
            A:"BBrowserX", A_en:"BBrowserX",
            B:"SpatialX", B_en:"SpatialX",
            C:"Talk2Data", C_en:"Talk2Data",
            D:"SmartBulk", D_en:"SmartBulk",
            ans:["A","B","C","D"],
            exp:"四者皆是：BBrowserX（單細胞）、SpatialX（空間）、Talk2Data（公開資料庫）、SmartBulk（bulk RNA-seq）。",
            exp_en:"All four: BBrowserX (single-cell), SpatialX (spatial), Talk2Data (public database), SmartBulk (bulk RNA-seq)." },
          { type:"tf",
            stem:"BioTuring 這類 GUI 平台完全取代了 Seurat / Scanpy，程式碼工具已無存在必要。",
            stem_en:"GUI platforms like BioTuring fully replace Seurat/Scanpy, making code tools unnecessary.",
            ans:"F",
            exp:"兩者互補而非取代。GUI 強在易用、速度與公開資料探索；程式碼工具彈性最高、可完全客製與重現。",
            exp_en:"They complement, not replace. GUI wins on ease/speed/public-data mining; code wins on flexibility and reproducibility." }
        ],
        "資料匯入與格式": [
          { type:"multi",
            stem:"BBrowserX 支援匯入下列哪些單細胞資料格式？（多選）",
            stem_en:"Which single-cell data formats can BBrowserX import? (multiple)",
            A:".h5ad (AnnData)", A_en:".h5ad (AnnData)",
            B:"Seurat 物件", B_en:"Seurat objects",
            C:"10x HDF5 (.h5)", C_en:"10x HDF5 (.h5)",
            D:"10x MTX bundle", D_en:"10x MTX bundle",
            ans:["A","B","C","D"],
            exp:"BBrowserX 支援 .h5ad、Seurat、10x HDF5 與 MTX bundle（matrix.mtx + barcodes.tsv + features.tsv）。",
            exp_en:"BBrowserX supports .h5ad, Seurat, 10x HDF5, and MTX bundles (matrix.mtx + barcodes.tsv + features.tsv)." },
          { type:"single",
            stem:"一個 10x MTX bundle 通常包含哪三個檔案？",
            stem_en:"A 10x MTX bundle usually contains which three files?",
            A:"matrix.mtx、barcodes.tsv、features(genes).tsv", A_en:"matrix.mtx, barcodes.tsv, features(genes).tsv",
            B:"fastq、bam、vcf", B_en:"fastq, bam, vcf",
            C:"pdf、csv、txt", C_en:"pdf, csv, txt",
            D:"只有一個 .xlsx", D_en:"just one .xlsx",
            ans:"A",
            exp:"MTX bundle = 稀疏表現矩陣 (matrix.mtx) + 細胞條碼 (barcodes.tsv) + 基因列表 (features/genes.tsv)。",
            exp_en:"An MTX bundle = sparse matrix (matrix.mtx) + cell barcodes (barcodes.tsv) + gene list (features/genes.tsv)." },
          { type:"single",
            stem:"單細胞的「表現矩陣 (count matrix)」通常是什麼結構？",
            stem_en:"A single-cell count matrix is typically what structure?",
            A:"基因 × 細胞的稀疏矩陣，多數元素為 0", A_en:"A sparse genes × cells matrix, mostly zeros",
            B:"一張影像", B_en:"An image",
            C:"一段 DNA 序列", C_en:"A DNA sequence",
            D:"密集的常態分佈矩陣", D_en:"A dense Gaussian matrix",
            ans:"A",
            exp:"單細胞資料是基因×細胞的稀疏 UMI 計數矩陣，因每個細胞只偵測到部分基因，大量為 0。",
            exp_en:"It's a sparse genes×cells UMI count matrix — each cell detects only some genes, so most entries are 0." },
          { type:"tf",
            stem:"BBrowserX 除了自己的資料外，也能匯入並分析來自 NCBI GEO 等已發表的資料集。",
            stem_en:"Besides your own data, BBrowserX can import and analyze published datasets (e.g., from NCBI GEO).",
            ans:"T",
            exp:"BBrowserX 可上傳並分析來自 NCBI GEO 等公開來源的已發表資料集。",
            exp_en:"BBrowserX can upload and analyze published datasets from public sources such as NCBI GEO." }
        ]
      },
      "BBrowserX 核心流程": {
        "品質管控 (QC)": [
          { type:"single",
            stem:"percent.mt（粒線體基因比例）過高，最常見的解讀為何？",
            stem_en:"What does a high percent.mt (mitochondrial fraction) most commonly indicate?",
            A:"細胞轉錄極為旺盛", A_en:"Extremely active transcription",
            B:"細胞可能死亡或瀕死", B_en:"The cell is likely dead or dying",
            C:"一定是 doublet", C_en:"Definitely a doublet",
            D:"定序深度不足", D_en:"Insufficient sequencing depth",
            ans:"B",
            exp:"細胞破裂時胞質 mRNA 外漏，粒線體 RNA 因雙層膜保留，使 MT% 上升，是判斷死活的關鍵指標。",
            exp_en:"On rupture, cytoplasmic mRNA leaks while mitochondrial RNA is retained, raising MT% — a viability signal." },
          { type:"single",
            stem:"在 BBrowserX 中設定 QC 閾值時，最佳做法是？",
            stem_en:"When setting QC thresholds in BBrowserX, best practice is to?",
            A:"直接套用固定的 5% / 200 / 4000，不用看圖", A_en:"Blindly apply fixed 5%/200/4000 without looking",
            B:"先用小提琴圖／散佈圖視覺化分佈，再依組織與資料決定閾值", B_en:"Visualize distributions (violin/scatter) first, then choose thresholds by tissue & data",
            C:"把所有細胞都保留", C_en:"Keep all cells",
            D:"把一半細胞隨機刪除", D_en:"Randomly delete half the cells",
            ans:"B",
            exp:"沒有放諸四海皆準的閾值；BBrowserX 的精神是先互動視覺化再設定，並避免過度過濾稀有族群。",
            exp_en:"No universal threshold exists; BBrowserX's ethos is visualize-then-threshold, avoiding over-filtering rare populations." },
          { type:"single",
            stem:"某細胞同時有極高的 nFeature_RNA 與極高的 nCount_RNA，最可能是？",
            stem_en:"A cell has very high nFeature_RNA AND nCount_RNA. Most likely it is?",
            A:"空液滴", A_en:"An empty droplet",
            B:"doublet（兩細胞同入一液滴）", B_en:"A doublet (two cells in one droplet)",
            C:"死細胞", C_en:"A dead cell",
            D:"環境 RNA", D_en:"Ambient RNA",
            ans:"B",
            exp:"基因數與 UMI 數同時異常偏高是 doublet 的典型特徵。",
            exp_en:"Simultaneously inflated gene and UMI counts are a hallmark of doublets." },
          { type:"tf",
            stem:"「被當前閾值過濾掉」的細胞，一定是死細胞或壞細胞。",
            stem_en:"A cell 'filtered by the current threshold' is definitely dead or bad.",
            ans:"F",
            exp:"「未通過」只代表在當前閾值下被移除，需配合生物學情境判斷，不等於一定是壞細胞。",
            exp_en:"'Filtered' just means removed under the current threshold; interpret with biology — it isn't automatically a bad cell." }
        ],
        "標準化與降維": [
          { type:"single",
            stem:"標準化 (normalization) 在單細胞分析中的主要目的是？",
            stem_en:"What is the main purpose of normalization in single-cell analysis?",
            A:"校正細胞間定序深度 (library size) 的差異，使細胞可比較", A_en:"Correct per-cell sequencing-depth (library size) differences so cells are comparable",
            B:"刪除所有基因", B_en:"Delete all genes",
            C:"增加細胞數量", C_en:"Increase the number of cells",
            D:"把資料變成影像", D_en:"Turn data into images",
            ans:"A",
            exp:"標準化校正各細胞捕獲到的總 UMI 差異，讓表現量在細胞間可比較。BBrowserX 主要採 log 標準化。",
            exp_en:"Normalization corrects differences in total UMIs per cell so expression is comparable; BBrowserX mainly uses log-normalization." },
          { type:"single",
            stem:"關於 PCA、UMAP 與 t-SNE 的關係，下列何者正確？",
            stem_en:"Which is correct about PCA, UMAP and t-SNE?",
            A:"PCA 先壓縮維度／去噪，UMAP 或 t-SNE 再把資料投影成 2D 視覺化", A_en:"PCA first compresses/denoises; UMAP or t-SNE then project to 2D for visualization",
            B:"三者都是分群演算法", B_en:"All three are clustering algorithms",
            C:"UMAP 是一種標準化方法", C_en:"UMAP is a normalization method",
            D:"t-SNE 用來過濾細胞", D_en:"t-SNE is used to filter cells",
            ans:"A",
            exp:"典型流程：PCA 降維去噪 → UMAP/t-SNE 投影成 2D。後兩者是視覺化，不是分群本身。",
            exp_en:"Typical flow: PCA denoises → UMAP/t-SNE project to 2D. The latter two are visualization, not clustering itself." },
          { type:"tf",
            stem:"在 UMAP 圖上，兩個相距很遠的 cluster 之間的「距離」可以被直接解讀為它們生物學差異的精確大小。",
            stem_en:"On a UMAP, the distance between two far-apart clusters can be read as the exact magnitude of their biological difference.",
            ans:"F",
            exp:"UMAP 保留局部結構較佳，全域距離不宜過度解讀；遠距離不等於差異的精確量化。",
            exp_en:"UMAP preserves local structure better; global distances shouldn't be over-interpreted as precise differences." },
          { type:"single",
            stem:"高變異基因 (HVGs) 的選擇在流程中扮演什麼角色？",
            stem_en:"What role does selecting highly variable genes (HVGs) play?",
            A:"挑出具高生物變異的基因作為 PCA/分群的特徵，降低噪音", A_en:"Pick high-variance genes as features for PCA/clustering, reducing noise",
            B:"刪除所有變異的基因", B_en:"Remove all variable genes",
            C:"把細胞標準化", C_en:"Normalize the cells",
            D:"計算粒線體比例", D_en:"Compute mitochondrial fraction",
            ans:"A",
            exp:"HVGs 聚焦於帶有生物訊號的基因，作為下游 PCA 與分群的核心輸入特徵。",
            exp_en:"HVGs focus on genes carrying biological signal, serving as key inputs to PCA and clustering." }
        ],
        "分群與批次校正": [
          { type:"single",
            stem:"BBrowserX 進行細胞分群時使用的社群偵測演算法是？",
            stem_en:"Which community-detection algorithm does BBrowserX use for clustering?",
            A:"Louvain（在 PCA 空間的 KNN 圖上）", A_en:"Louvain (on a KNN graph in PCA space)",
            B:"線性迴歸", B_en:"Linear regression",
            C:"隨機森林", C_en:"Random forest",
            D:"傅立葉轉換", D_en:"Fourier transform",
            ans:"A",
            exp:"BBrowserX 在 PCA 空間建立 KNN 圖，再以 Louvain 進行社群偵測得到 cluster。",
            exp_en:"BBrowserX builds a KNN graph in PCA space, then applies Louvain community detection to obtain clusters." },
          { type:"single",
            stem:"提高分群的 resolution 參數會有什麼效果？",
            stem_en:"What happens as you raise the clustering resolution parameter?",
            A:"cluster 數變多、每群變小（更細）", A_en:"More, smaller clusters (finer)",
            B:"cluster 數變少、每群變大", B_en:"Fewer, larger clusters",
            C:"完全不影響 cluster 數", C_en:"No effect on cluster count",
            D:"刪除細胞", D_en:"Deletes cells",
            ans:"A",
            exp:"resolution 越高，分群越細、cluster 數越多；沒有唯一正確值，需以 marker 驗證。",
            exp_en:"Higher resolution yields finer, more numerous clusters; there's no single right value — validate with markers." },
          { type:"single",
            stem:"整合多樣本／多批次時，BBrowserX 用來做批次校正的方法是？",
            stem_en:"For integrating multiple samples/batches, which batch-correction method does BBrowserX use?",
            A:"Harmony", A_en:"Harmony",
            B:"BLAST", B_en:"BLAST",
            C:"Bowtie", C_en:"Bowtie",
            D:"GATK", D_en:"GATK",
            ans:"A",
            exp:"BBrowserX 主要以 Harmony 進行批次校正／整合，目標是移除批次效應同時保留真實生物差異。",
            exp_en:"BBrowserX mainly uses Harmony for batch correction/integration — removing batch effects while preserving true biology." },
          { type:"tf",
            stem:"批次校正越強越好，過度校正沒有任何風險。",
            stem_en:"Stronger batch correction is always better, with no risk of over-correction.",
            ans:"F",
            exp:"過度校正可能把真實的生物差異一起抹除；需在移除批次與保留生物訊號間取得平衡。",
            exp_en:"Over-correction can erase real biology; you must balance removing batch effects against preserving signal." }
        ],
        "細胞註釋 (Annotation)": [
          { type:"single",
            stem:"BBrowserX 的自動細胞類型預測 (MetaReference) 建立在什麼基礎上？",
            stem_en:"BBrowserX's automatic cell-type prediction (MetaReference) is built on what?",
            A:"BioTuring 精選、逾 1 億單細胞的參考資料庫（可分 54 類 / 183 亞型）", A_en:"BioTuring's curated reference of 100M+ single cells (54 types / 183 subtypes)",
            B:"隨機猜測", B_en:"Random guessing",
            C:"單一基因的表現", C_en:"A single gene's expression",
            D:"細胞的顏色", D_en:"The cell's color",
            ans:"A",
            exp:"MetaReference 以逾 1 億單細胞的參考資料庫做 label transfer，可分類 54 種細胞類型與 183 種亞型。",
            exp_en:"MetaReference transfers labels from a 100M+ cell reference, classifying 54 cell types and 183 subtypes." },
          { type:"single",
            stem:"下列哪組 marker 常用來標記 T 細胞？",
            stem_en:"Which markers are commonly used to identify T cells?",
            A:"CD3D / CD3E", A_en:"CD3D / CD3E",
            B:"MS4A1 / CD79A", B_en:"MS4A1 / CD79A",
            C:"LYZ / CD14", C_en:"LYZ / CD14",
            D:"PECAM1", D_en:"PECAM1",
            ans:"A",
            exp:"CD3D/CD3E 標記 T 細胞；MS4A1/CD79A 為 B 細胞、LYZ/CD14 為單核球、PECAM1 為內皮細胞。",
            exp_en:"CD3D/CD3E mark T cells; MS4A1/CD79A B cells; LYZ/CD14 monocytes; PECAM1 endothelial cells." },
          { type:"tf",
            stem:"自動預測的細胞類型應該直接採信，不需要再用 marker 或生物學情境驗證。",
            stem_en:"Automatic cell-type predictions should be trusted directly, with no marker or biological validation.",
            ans:"F",
            exp:"自動註釋可能因參考偏差把罕見／新型細胞誤標；務必用 marker 與生物學情境驗證。",
            exp_en:"Auto-annotation can mislabel rare/novel cells due to reference bias; always validate with markers and biology." },
          { type:"single",
            stem:"BBrowserX Pro 額外提供的臨床相關預測功能是？",
            stem_en:"Which clinical-oriented prediction does BBrowserX Pro additionally offer?",
            A:"癌細胞預測 (cancer cell prediction)", A_en:"Cancer cell prediction",
            B:"天氣預測", B_en:"Weather prediction",
            C:"股價預測", C_en:"Stock price prediction",
            D:"蛋白質摺疊預測", D_en:"Protein folding prediction",
            ans:"A",
            exp:"Pro 版含進階多模態與臨床模組，包括癌細胞預測。",
            exp_en:"Pro includes advanced multimodal and clinical modules, including cancer cell prediction." }
        ],
        "差異表達與 Venice": [
          { type:"single",
            stem:"Venice 相對於傳統只比較「平均表現」方法的關鍵創新是？",
            stem_en:"What is Venice's key innovation over methods that only compare mean expression?",
            A:"它比較整個表現「分佈」，能偵測 DE/DP/DM/DB 四種差異型態", A_en:"It compares the whole expression distribution, detecting DE/DP/DM/DB patterns",
            B:"它只看最高表現的一個細胞", B_en:"It looks at only the single highest-expressing cell",
            C:"它不需要任何統計", C_en:"It requires no statistics",
            D:"它把所有基因視為相同", D_en:"It treats all genes as identical",
            ans:"A",
            exp:"單細胞群體常是多種細胞狀態的混合，單一平均值不足以代表；Venice 比較分佈並辨識 DE/DP/DM/DB。",
            exp_en:"A population is often a mixture of states; a single mean is insufficient. Venice compares distributions and detects DE/DP/DM/DB." },
          { type:"multi",
            stem:"BBrowserX 的差異表達分析可使用下列哪些方法？（多選）",
            stem_en:"Which DE methods can BBrowserX use? (multiple)",
            A:"Venice（BioTuring 自研）", A_en:"Venice (BioTuring's own)",
            B:"t-test", B_en:"t-test",
            C:"Wilcoxon rank-sum", C_en:"Wilcoxon rank-sum",
            D:"擲骰子隨機", D_en:"Rolling dice at random",
            ans:["A","B","C"],
            exp:"BBrowserX 提供 Venice 以及標準的 t-test 與 Wilcoxon 檢定。",
            exp_en:"BBrowserX offers Venice plus standard t-test and Wilcoxon tests." },
          { type:"tf",
            stem:"兩組細胞某基因的「平均表現量相同」，就一定代表兩組在該基因上沒有任何生物學差異。",
            stem_en:"If a gene's mean expression is equal between two groups, there can be no biological difference in that gene.",
            ans:"F",
            exp:"平均相同但分佈可不同（如表現細胞比例 DP 或雙峰 DM）；這正是 Venice 能捕捉、平均法會漏掉的情況。",
            exp_en:"Equal means can hide different distributions (e.g., DP proportion or DM modality) — exactly what Venice catches and mean-based tests miss." },
          { type:"single",
            stem:"解讀差異表達結果時，下列哪個觀念最正確？",
            stem_en:"When interpreting DE results, which idea is most correct?",
            A:"統計顯著 ≠ 生物學重要；還要看 log2FC 與生物學脈絡", A_en:"Statistical significance ≠ biological importance; also weigh log2FC and biology",
            B:"只要 p 值小就一定重要", B_en:"A small p-value alone means it's important",
            C:"log2FC 可以完全忽略", C_en:"log2FC can be ignored entirely",
            D:"樣本間的偽重複 (pseudoreplication) 不需注意", D_en:"Pseudoreplication across samples needn't be considered",
            ans:"A",
            exp:"應同時看效應量 (log2FC)、校正後 p 值與生物脈絡，並留意跨樣本比較的偽重複問題。",
            exp_en:"Weigh effect size (log2FC), adjusted p-value and biology together, and watch pseudoreplication across samples." }
        ]
      },
      "進階與生態系": {
        "軌跡與細胞通訊": [
          { type:"single",
            stem:"BBrowserX 進行軌跡 (trajectory / pseudotime) 分析所採用的方法是？",
            stem_en:"Which method does BBrowserX use for trajectory / pseudotime analysis?",
            A:"Monocle 2", A_en:"Monocle 2",
            B:"Harmony", B_en:"Harmony",
            C:"Louvain", C_en:"Louvain",
            D:"Venice", D_en:"Venice",
            ans:"A",
            exp:"BBrowserX 以 Monocle 2 推估細胞沿發育／分化路徑的 pseudotime 與分支點。",
            exp_en:"BBrowserX uses Monocle 2 to infer pseudotime and branch points along developmental/differentiation paths." },
          { type:"single",
            stem:"關於 pseudotime（擬時序），下列何者正確？",
            stem_en:"Which is correct about pseudotime?",
            A:"它是依轉錄漸變推估的相對順序，並非真實的時鐘時間", A_en:"It's an inferred relative ordering from gradual transcriptomic change, not real clock time",
            B:"它就是細胞的實際年齡（小時）", B_en:"It is the cell's actual age in hours",
            C:"它與分化過程無關", C_en:"It is unrelated to differentiation",
            D:"它需要活體攝影才能計算", D_en:"It requires live imaging to compute",
            ans:"A",
            exp:"pseudotime 是計算推估的相對順序，需有生物學上連續的過程與合理起點，不等於真實時間。",
            exp_en:"Pseudotime is an inferred relative ordering; it needs a biologically continuous process and sensible root — not real time." },
          { type:"single",
            stem:"BBrowserX 的細胞通訊分析利用哪個 ligand–receptor 資料庫？",
            stem_en:"BBrowserX's cell-communication analysis leverages which ligand–receptor database?",
            A:"CellChat", A_en:"CellChat",
            B:"KEGG", B_en:"KEGG",
            C:"GenBank", C_en:"GenBank",
            D:"UniProt", D_en:"UniProt",
            ans:"A",
            exp:"BBrowserX 以 CellChat 的 ligand–receptor 資料庫推估細胞類型間的訊號交互作用。",
            exp_en:"BBrowserX uses the CellChat ligand–receptor database to infer signaling between cell types." },
          { type:"tf",
            stem:"以 mRNA 共表現推估的細胞通訊結果，等同於證明兩細胞間確實存在功能性訊號傳遞。",
            stem_en:"Cell-communication inferred from mRNA co-expression proves functional signaling between two cells.",
            ans:"F",
            exp:"mRNA 共表現只是訊號的間接代理，需實驗驗證，不能直接當成功能性交互作用的證明。",
            exp_en:"mRNA co-expression is only a proxy for signaling; it needs experimental validation, not proof by itself." }
        ],
        "多模態與免疫圖譜": [
          { type:"single",
            stem:"CITE-seq / ADT (Antibody-Derived Tags) 能同時測量細胞的什麼？",
            stem_en:"CITE-seq / ADT (Antibody-Derived Tags) simultaneously measures what in a cell?",
            A:"RNA 與細胞表面蛋白", A_en:"RNA and cell-surface protein",
            B:"只有 DNA 甲基化", B_en:"Only DNA methylation",
            C:"只有染色質可及性", C_en:"Only chromatin accessibility",
            D:"細胞的重量", D_en:"The cell's weight",
            ans:"A",
            exp:"ADT 提供表面蛋白讀值，與 RNA 互補——因為蛋白量不一定等於 mRNA 量。",
            exp_en:"ADT gives surface-protein readouts complementing RNA — protein levels don't always match mRNA." },
          { type:"single",
            stem:"單細胞 TCR/BCR（免疫 repertoire）分析的核心價值是？",
            stem_en:"The core value of single-cell TCR/BCR (immune repertoire) analysis is?",
            A:"把每個 T/B 細胞的受體 clonotype 與其轉錄表型連結（如擴增的耗竭 CD8 T 細胞）", A_en:"Linking each T/B cell's receptor clonotype to its transcriptomic phenotype (e.g., expanded exhausted CD8 T cells)",
            B:"測量粒線體比例", B_en:"Measuring mitochondrial fraction",
            C:"計算 UMAP 座標", C_en:"Computing UMAP coordinates",
            D:"做批次校正", D_en:"Performing batch correction",
            ans:"A",
            exp:"TCR/BCR 分析可將 clonotype 與細胞表型連結，例如辨識 clonal expansion 對應的功能狀態。",
            exp_en:"TCR/BCR analysis links clonotypes to phenotypes, e.g., identifying the functional state of expanded clones." },
          { type:"single",
            stem:"細胞 hashing / demultiplexing 使用 HTO (hashtag oligos) 的目的是？",
            stem_en:"Cell hashing / demultiplexing with HTOs (hashtag oligos) is used to?",
            A:"把多個樣本混合在同一次 run，事後將每個細胞歸回其樣本並協助偵測 doublet", A_en:"Pool multiple samples in one run, then assign each cell back to its sample and help flag doublets",
            B:"增加基因數", B_en:"Increase gene counts",
            C:"清除粒線體基因", C_en:"Remove mitochondrial genes",
            D:"取代 PCA", D_en:"Replace PCA",
            ans:"A",
            exp:"HTO 讓多樣本共同定序，demultiplexing 依 HTO 將細胞歸回樣本，並能標記跨樣本 doublet。",
            exp_en:"HTOs let samples be pooled; demultiplexing assigns cells back by HTO and flags cross-sample doublets." },
          { type:"tf",
            stem:"TCR/BCR repertoire 分析適用於所有細胞類型，包括上皮細胞與神經元。",
            stem_en:"TCR/BCR repertoire analysis applies to all cell types, including epithelial cells and neurons.",
            ans:"F",
            exp:"TCR/BCR 只存在於淋巴球（T/B 細胞），對上皮或神經元等非淋巴球無意義。",
            exp_en:"TCR/BCR exist only in lymphocytes (T/B cells); they're meaningless for epithelial or neuronal cells." }
        ],
        "SpatialX 空間分析": [
          { type:"single",
            stem:"相較於解離式 scRNA-seq，空間轉錄組最關鍵的額外資訊是？",
            stem_en:"Compared with dissociated scRNA-seq, what key extra information does spatial data add?",
            A:"細胞在組織中的「位置」與鄰近關係", A_en:"The cells' location in tissue and their neighbors",
            B:"更高的定序深度", B_en:"Higher sequencing depth",
            C:"更多的粒線體基因", C_en:"More mitochondrial genes",
            D:"更小的檔案", D_en:"Smaller files",
            ans:"A",
            exp:"空間資料保留細胞在組織中的位置，可在組織結構脈絡與鄰近細胞的情境下詮釋。",
            exp_en:"Spatial data preserves where cells sit in tissue, enabling interpretation in architectural and neighborhood context." },
          { type:"multi",
            stem:"SpatialX 支援下列哪些空間技術平台？（多選）",
            stem_en:"Which spatial technologies does SpatialX support? (multiple)",
            A:"10x Visium", A_en:"10x Visium",
            B:"10x Xenium", B_en:"10x Xenium",
            C:"NanoString CosMx", C_en:"NanoString CosMx",
            D:"Vizgen MERFISH", D_en:"Vizgen MERFISH",
            ans:["A","B","C","D"],
            exp:"SpatialX 支援 Visium、Xenium、CosMx、MERFISH，另含 GeoMx DSP 與 Slide-seq。",
            exp_en:"SpatialX supports Visium, Xenium, CosMx, MERFISH, plus GeoMx DSP and Slide-seq." },
          { type:"single",
            stem:"下列關於「spot 式 (如 Visium)」與「單細胞影像式 (如 Xenium/CosMx)」的敘述何者正確？",
            stem_en:"Which statement about spot-based (e.g., Visium) vs single-cell imaging (e.g., Xenium/CosMx) is correct?",
            A:"spot 式一個點可能含多個細胞、常需 deconvolution；影像式有單細胞解析度但基因為 targeted panel", A_en:"Spot-based points may contain multiple cells (often need deconvolution); imaging has single-cell resolution but a targeted gene panel",
            B:"兩者完全相同", B_en:"They are identical",
            C:"影像式一定涵蓋全轉錄組", C_en:"Imaging always covers the whole transcriptome",
            D:"spot 式有單細胞解析度", D_en:"Spot-based has single-cell resolution",
            ans:"A",
            exp:"spot/region 式（Visium、GeoMx）解析度較粗、常需 deconvolution；影像式（Xenium、CosMx、MERFISH）為單細胞解析度但基因是 targeted panel。",
            exp_en:"Spot/region methods (Visium, GeoMx) are coarser and often need deconvolution; imaging (Xenium, CosMx, MERFISH) is single-cell but uses targeted panels." },
          { type:"tf",
            stem:"SpatialX 是無程式碼的 Windows 平台，讓研究者免寫 R 也能分析空間資料。",
            stem_en:"SpatialX is a no-code Windows platform, letting researchers analyze spatial data without coding in R.",
            ans:"T",
            exp:"SpatialX（前身 Lens）為無程式碼、Windows-based 的空間分析平台。",
            exp_en:"SpatialX (formerly Lens) is a no-code, Windows-based spatial analysis platform." }
        ],
        "Talk2Data 資料庫": [
          { type:"single",
            stem:"Talk2Data 的核心用途是？",
            stem_en:"What is Talk2Data's core purpose?",
            A:"在不自己做實驗的情況下，跨研究挖掘大型精選的公開單細胞／空間資料", A_en:"Mining large curated public single-cell/spatial data across studies without generating your own",
            B:"控制定序儀器", B_en:"Controlling the sequencer",
            C:"合成 DNA", C_en:"Synthesizing DNA",
            D:"設計 PCR 引子", D_en:"Designing PCR primers",
            ans:"A",
            exp:"Talk2Data 是建於龐大精選公開資料庫的分析中樞，支援跨研究分析與 Gene Search。",
            exp_en:"Talk2Data is an analytics hub over a large curated public database, supporting cross-study analysis and Gene Search." },
          { type:"single",
            stem:"Talk2Data 的 Gene Search 讓你能做什麼？",
            stem_en:"What does Talk2Data's Gene Search let you do?",
            A:"查詢某基因在整個資料庫中跨組織／細胞類型的表現", A_en:"Query a gene's expression across tissues/cell types over the whole database",
            B:"編輯基因序列", B_en:"Edit gene sequences",
            C:"刪除資料庫", C_en:"Delete the database",
            D:"訓練定序儀", D_en:"Train the sequencer",
            ans:"A",
            exp:"Gene Search 可跨整個 BioTuring 資料庫查詢基因表現，快速定位在哪些組織／細胞高表現。",
            exp_en:"Gene Search queries a gene's expression across the whole database, quickly locating where it's highly expressed." },
          { type:"tf",
            stem:"公開資料一經 BioTuring 精選收錄後，就完全沒有批次、平台或註釋差異，可以無條件直接跨研究比較。",
            stem_en:"Once curated by BioTuring, public data has no batch/platform/annotation differences and can be compared across studies unconditionally.",
            ans:"F",
            exp:"精選不等於完美；跨研究仍有批次、平台與註釋標準的異質性，比較時需回看原始研究脈絡。",
            exp_en:"Curated isn't perfect; cross-study heterogeneity (batch, platform, annotation) remains — always check the original context." },
          { type:"single",
            stem:"下列哪個情境最適合用 Talk2Data 而非 BBrowserX？",
            stem_en:"Which scenario best fits Talk2Data rather than BBrowserX?",
            A:"想在 120M+ 已發表細胞中驗證某發現，且沒有自己的原始資料", A_en:"Validating a finding across 120M+ published cells without your own raw data",
            B:"分析自己剛產出的 10x 原始矩陣", B_en:"Analyzing your own freshly generated 10x matrix",
            C:"對自己的樣本做 QC 過濾", C_en:"QC-filtering your own samples",
            D:"匯入自己的 Seurat 物件跑分群", D_en:"Importing your own Seurat object to cluster",
            ans:"A",
            exp:"Talk2Data 專為跨研究挖掘公開資料而設計；分析自有原始資料則用 BBrowserX。",
            exp_en:"Talk2Data is for mining public data across studies; analyzing your own raw data is BBrowserX's job." }
        ]
      }
    }
  }
};
